### ISSUE TITLE
Bruker_QSM folder is not available.

### ISSUE THREAD

**Issue by Bella1999999999** [hanwencat/NLLS_fitting#1]
Hi,

I'm reading your NLLS fitting for myelin water imaging, and feel it is very useful. However, I cannot get access to Bruker_QSM folder, which made me impossible to read codes for k-space reconstruction or test phantom fitting. Could you please give me the access?

Thanks!

**Comment by hanwencat** [comment]
Hi,

Thanks for your interest! 

Sorry, I’m not in position to grant you the access to the Bruker_QSM folder because that folder contains code developed by others. However, if you really want to use our fitting program, you can make a request to my supervisor Prof. David Rudko ***@***.*** ) to discuss the possibilities of collaboration.

By the way, the preprocessing part is not required if you just want to fit the magnitude mGRE data. For complex data fitting, the code may also work without the preprocessing part but minor modifications are needed (i.e. set the initial frequency shift manually).

Hope it makes sense to you.


Best,
Kevin

**Comment by Bella1999999999** [comment]
Thanks for your suggestion!
